### ISSUE TITLE
Ambiguity between openpnp opencv and openpnp-capture-java

### ISSUE THREAD

**Issue by mdagraca** [openpnp/openpnp-capture-java#1]
Hi, 
I'm using openpnp opencv and I'm trying to use openpnp-capture-java but I have this exception:

objc[7044]: Class PlatformAVCaptureDelegate is implemented in both /var/folders/j1/_q1t_00d0fg66bsgtgf8zjgc0000gp/T/jna-74113754/jna5880730534395773134.tmp and /var/folders/j1/_q1t_00d0fg66bsgtgf8zjgc0000gp/T/jna-74113754/jna8776725927432952429.tmp. One of the two will be used. Which one is undefined.

when I do this:
           OpenPnpCapture capture = new OpenPnpCapture();
	    for(CaptureDevice device : capture.getDevices()) {
	    		System.out.println(device.getName() + " " + device.getUniqueId());
	    }
My project maven dependencies are:
<dependency>
      <groupId>org.openpnp</groupId>
      <artifactId>opencv</artifactId>
      <version>3.2.0-1</version>
    </dependency>
<dependency>
	<groupId>org.openpnp</groupId>
	<artifactId>openpnp-capture-java</artifactId>
	 <version>0.0.12</version>
</dependency>
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>4.5.0</version>
</dependency>
Is there a way to add exclusions in maven pom to avoid this error?
Thanks

**Comment by mdagraca** [comment]
After the warning, when then capture object is released, the java app crash with

Stack: [0x00007fff5c528000,0x00007fff5cd28000],  sp=0x00007fff5cd23218,  free space=8172k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libobjc.A.dylib+0x14e9]  objc_msgSend+0x29
C  [CoreFoundation+0x48c12]  _CFAutoreleasePoolPop+0x32
C  [Foundation+0x189ea]  -[NSAutoreleasePool drain]+0x99
C  [Foundation+0x76fde]  __NSThreadPerformPerform+0x117
C  [CoreFoundation+0xaa881]  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__+0x11
C  [CoreFoundation+0x89fbc]  __CFRunLoopDoSources0+0x22c
C  [CoreFoundation+0x894df]  __CFRunLoopRun+0x39f
C  [CoreFoundation+0x88ed8]  CFRunLoopRunSpecific+0x128
C  [HIToolbox+0x30935]  RunCurrentEventLoopInMode+0xeb
C  [HIToolbox+0x3076f]  ReceiveNextEventCommon+0x1b0
C  [HIToolbox+0x305af]  _BlockUntilNextEventMatchingListInModeWithFilter+0x47
C  [AppKit+0x48df6]  _DPSNextEvent+0x42b
C  [AppKit+0x48226]  -[NSApplication _nextEventMatchingEventMask:untilDate:inMode:dequeue:]+0x1c6
C  [AppKit+0x3cd80]  -[NSApplication run]+0x2aa
C  [libglass.dylib+0x4f47]  -[GlassApplication runLoop:]+0x6f7
C  [Foundation+0x76fde]  __NSThreadPerformPerform+0x117
C  [CoreFoundation+0xaa881]  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__+0x11
C  [CoreFoundation+0x89fbc]  __CFRunLoopDoSources0+0x22c
C  [CoreFoundation+0x894df]  __CFRunLoopRun+0x39f
C  [CoreFoundation+0x88ed8]  CFRunLoopRunSpecific+0x128
C  [java+0x6463]  CreateExecutionEnvironment+0x367
C  [java+0x21ac]  JLI_Launch+0x7a0
C  [java+0x84c0]  main+0x65
C  [java+0x1a04]  start+0x34
C  0x0000000000000007

**Comment by vonnieda** [comment]
HI @mdagraca, I've noticed this error before but not the crash. That said, other people have reported BSODs (on Windows) after exiting OpenPnP, so I wonder if this might be related. Unfortunately, I don't have an answer on how to fix this. If you can come up with anything I'd be happy to accept a PR.

**Comment by mdagraca** [comment]
I think the crash is because the garbage collector is trying to release an object already released. It happens to me too when I release the videoCapture object with openpnp-opencv.
About the initial problem, it's because both openpnp jars are using the same native lib (dylib, I'm testing in Mac). 
May be we can add  to the pom.xml that some of the jars not use these libs.
Something like: 
```
<dependency>
      <groupId>org.openpnp</groupId>
      <artifactId>openpnp-capture-java</artifactId>
       <version>0.0.12</version>
       <exclusions>
	       <exclusion>
	             <groupId>native lib pacage</groupId>
		     <artifactId>ID</artifactId>
	       </exclusion>
       </exclusions>
</dependency>
```
Is it possible?

**Comment by vonnieda** [comment]
Hi @mdagraca, that sounds like a good solution, but isn't this something you would add to your project? Or are you proposing we add it to the capture pom?

**Comment by vonnieda** [comment]
@mdagraca It looks like the "implemented in both" error is harmless, so there may be something else happening. See https://stackoverflow.com/questions/43003012/class-javalaunchhelper-is-implemented-in-two-places. I'm checking now if upgrading to Java 8 - 152 will remove the error and let me focus on what is causing the crash. I'm also seeing a crash in a simple test program using *only* openpnp-capture-java and not opencv. I'll followup soon.

**Comment by vonnieda** [comment]
Note to self: I've tracked this down to a problem that appeared between versions 0.0.4 and 0.0.5. Running the code example above causes a crash on exit in 0.0.5 but works fine on all versions prior. 

Confirmed that it's definitely a crash on exit. Adding a 10 second delay before exiting from main delays the crash by 10 seconds. So this seems like a finalizer type issue.

**Comment by vonnieda** [comment]
Okay, it seems like something in the Travis build process may be causing this. I can reproduce the error by building a local copy of the Java bindings @ 0.0.5 and targeting the released native 0.0.5, but if I build native 0.0.5 locally and use that it seems to resolve the error.

**Comment by vonnieda** [comment]
Scratch that - still fails once fully built and tested against the jar, so it does appear to be related more to the extraction of the temporary binary and that being freed.

**Comment by mdagraca** [comment]
The java crash releasing the video capture object happened to me with opencv too, no only with openpnp-capture-java.
About the modification in pom.xml, it was a suggestion to see if is possible you tell me how to avoid the incompatibilities between both libs.
Thank you

**Comment by mdagraca** [comment]
It happens only in Mac, with Windows works ok

**Comment by vonnieda** [comment]
If this is still an issue, please re-open.
